# Generated by Django 2.2.7 on 2020-01-03 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aktor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=25)),
                ('nazwisko', models.CharField(max_length=25)),
                ('pochodzenie', models.CharField(choices=[('POLSKA', 'Polska'), ('FRANCJA', 'Francja'), ('USA', 'Usa'), ('NIEMCY', 'Niemcy'), ('WIELKA BRYTANIA', 'Wielka Brytania'), ('DANIA', 'Dania'), ('AZJA', 'Azja'), ('INNE', 'Inne')], default='POLSKA', max_length=25)),
                ('dataUrodzenia', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=25)),
                ('dataWydania', models.DateField()),
                ('ocena', models.CharField(choices=[('JEDEN', '1'), ('DWA', '2'), ('TRZY', '3'), ('CZWARTY', '4'), ('PIEC', '5'), ('CZESC', '6'), ('SIEDEM', '7'), ('OSIEM', '8'), ('DZIEWIEC', '9'), ('DZIESIEC', '10')], default='JEDEN', max_length=20)),
                ('fabula', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='gatunek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(choices=[('DRAMAT', 'dramat'), ('THRILLER', 'thriller'), ('DOKUMENT', 'dokument'), ('AKCJA', 'akcja'), ('HORROR', 'horror'), ('SCIENCE FICTION', 'science fiction'), ('ANIMOWANY', 'animowany')], default='DRAMAT', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='rezyser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=25)),
                ('nazwisko', models.CharField(max_length=25)),
                ('pochodzenie', models.CharField(choices=[('POLSKA', 'Polska'), ('FRANCJA', 'Francja'), ('USA', 'Usa'), ('NIEMCY', 'Niemcy'), ('WIELKA BRYTANIA', 'Wielka Brytania'), ('DANIA', 'Dania'), ('AZJA', 'Azja'), ('INNE', 'Inne')], default='POLSKA', max_length=25)),
                ('dataUrodzenia', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='filmgatunek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.CharField(max_length=45)),
                ('idFilm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.film')),
                ('idGatunek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.gatunek')),
            ],
        ),
        migrations.CreateModel(
            name='filmaktor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.CharField(max_length=45)),
                ('idAktor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.aktor')),
                ('idFilm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.film')),
            ],
        ),
    ]
