# Generated by Django 2.2.7 on 2020-01-28 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=25)),
                ('dataWydania', models.DateField()),
                ('gatunek', models.CharField(choices=[('DRAMAT', 'dramat'), ('THRILLER', 'thriller'), ('DOKUMENT', 'dokument'), ('AKCJA', 'akcja'), ('HORROR', 'horror'), ('SCIENCE FICTION', 'science fiction'), ('ANIMOWANY', 'animowany')], default='DRAMAT', max_length=20)),
                ('fabula', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='osoba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=25)),
                ('nazwisko', models.CharField(max_length=25)),
                ('pochodzenie', models.CharField(choices=[('POLSKA', 'Polska'), ('FRANCJA', 'Francja'), ('USA', 'Usa'), ('NIEMCY', 'Niemcy'), ('WIELKA BRYTANIA', 'Wielka Brytania'), ('DANIA', 'Dania'), ('AZJA', 'Azja'), ('INNE', 'Inne')], default='POLSKA', max_length=25)),
                ('dataUrodzenia', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ocena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocena', models.CharField(choices=[('JEDEN', '1'), ('DWA', '2'), ('TRZY', '3'), ('CZWARTY', '4'), ('PIEC', '5'), ('CZESC', '6'), ('SIEDEM', '7'), ('OSIEM', '8'), ('DZIEWIEC', '9'), ('DZIESIEC', '10')], default='JEDEN', max_length=20)),
                ('recenzja', models.CharField(max_length=200)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.film')),
                ('uzytkownik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uzytkownik', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='filmosoba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rola', models.CharField(choices=[('aktor', 'AKTOR'), ('rezyser', 'REZYSER')], default='AKTOR', max_length=20)),
                ('Film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.film')),
                ('Osoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.osoba')),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='osoba',
            field=models.ManyToManyField(through='biblio.filmosoba', to='biblio.osoba'),
        ),
    ]
