# Generated by Django 2.2.7 on 2020-01-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='aktor',
            field=models.ManyToManyField(through='biblio.filmaktor', to='biblio.aktor'),
        ),
        migrations.AddField(
            model_name='film',
            name='gatunek',
            field=models.ManyToManyField(through='biblio.filmgatunek', to='biblio.gatunek'),
        ),
    ]
