# Generated by Django 2.2.7 on 2020-01-03 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0002_auto_20200103_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='filmrezyser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.CharField(max_length=45)),
                ('idFilm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.film')),
                ('idRezyser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.rezyser')),
            ],
        ),
    ]
