# Generated by Django 2.2.7 on 2020-01-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0003_filmrezyser'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='rezyser',
            field=models.ManyToManyField(through='biblio.filmrezyser', to='biblio.rezyser'),
        ),
    ]
